from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 689)
        MainWindow.setStyleSheet("body{background:url(:/image-bg/bgimg.webp);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 391, 631))
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setAutoFillBackground(True)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(120, 20, 358, 36))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Titulo.setFont(font)
        self.Titulo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Titulo.setAutoFillBackground(False)
        self.Titulo.setStyleSheet("color: rgb(42, 140, 85);")
        self.Titulo.setObjectName("Titulo")
        self.Seleccionar = QtWidgets.QPushButton(self.centralwidget)
        self.Seleccionar.setGeometry(QtCore.QRect(140, 70, 141, 28))
        self.Seleccionar.setStyleSheet("color: rgb(42, 140, 85);")
        self.Seleccionar.setObjectName("Seleccionar")
        self.Analizar = QtWidgets.QPushButton(self.centralwidget)
        self.Analizar.setGeometry(QtCore.QRect(310, 70, 141, 28))
        self.Analizar.setStyleSheet("color: rgb(42, 140, 85);")
        self.Analizar.setObjectName("Analizar")
        self.Imagen_planta = QtWidgets.QLabel(self.centralwidget)
        self.Imagen_planta.setGeometry(QtCore.QRect(140, 120, 300, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Imagen_planta.setFont(font)
        self.Imagen_planta.setStyleSheet("border: 2px solid #2A8C55;\n"
"background-color: rgb(221, 221, 221);")
        self.Imagen_planta.setText("")
        self.Imagen_planta.setObjectName("Imagen_planta")
        self.Nombre_planta = QtWidgets.QLabel(self.centralwidget)
        self.Nombre_planta.setGeometry(QtCore.QRect(140, 440, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Nombre_planta.setFont(font)
        self.Nombre_planta.setAutoFillBackground(False)
        self.Nombre_planta.setStyleSheet("color: rgb(42, 140, 85);")
        self.Nombre_planta.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Nombre_planta.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Nombre_planta.setText("")
        self.Nombre_planta.setTextFormat(QtCore.Qt.AutoText)
        self.Nombre_planta.setAlignment(QtCore.Qt.AlignCenter)
        self.Nombre_planta.setObjectName("Nombre_planta")
        self.Confianza = QtWidgets.QLabel(self.centralwidget)
        self.Confianza.setGeometry(QtCore.QRect(140, 470, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Confianza.setFont(font)
        self.Confianza.setStyleSheet("color: rgb(116, 116, 116);")
        self.Confianza.setText("")
        self.Confianza.setAlignment(QtCore.Qt.AlignCenter)
        self.Confianza.setObjectName("Confianza")
        self.Caracteristicas = QtWidgets.QLabel(self.centralwidget)
        self.Caracteristicas.setGeometry(QtCore.QRect(140, 540, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Caracteristicas.setFont(font)
        self.Caracteristicas.setStyleSheet("border: 2px solid #2A8C55;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(221, 221, 221);")
        self.Caracteristicas.setText("")
        self.Caracteristicas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Caracteristicas.setWordWrap(True)
        self.Caracteristicas.setIndent(-1)
        self.Caracteristicas.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Caracteristicas.setObjectName("Caracteristicas")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 510, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 591, 631))
        self.label_2.setStyleSheet("background:url(:/image-bg/bgimg.webp);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.Titulo.raise_()
        self.Seleccionar.raise_()
        self.Analizar.raise_()
        self.Imagen_planta.raise_()
        self.Nombre_planta.raise_()
        self.Confianza.raise_()
        self.Caracteristicas.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titulo.setText(_translate("MainWindow", "DETECTOR DE PLANTAS"))
        self.Seleccionar.setText(_translate("MainWindow", "Selecciona la Imagen"))
        self.Analizar.setText(_translate("MainWindow", "Analiza la Imagen"))
        self.label_7.setText(_translate("MainWindow", "Consejos:"))
import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())